version: "3.9"

services:
  spring-dev-server:
    image: openjdk:16-jdk-slim
    working_dir: /trabacco-server
    command: /trabacco-server/mvnw spring-boot:run
    volumes:
      - ./server:/trabacco-server:ro
      - trabacco-data:/trabacco-server/data
      - trabacco-server-target:/trabacco-server/target
      - trabacco-server-m2:/root/.m2
    ports:
      - 8080:8080

  chart-dev-server:
    image: node:current-alpine3.13
    working_dir: /trabacco-chart
    command: /bin/sh -c "npm ci && npm run dev"
    volumes:
      - ./client/chart-generator:/trabacco-chart:ro
      - /trabacco-chart/node_modules
      - /trabacco-chart/out
    ports:
      - 8081:8081

  css-dev-server:
    image: node:current-alpine3.13
    working_dir: /trabacco-css
    command: /bin/sh -c "npm ci && npm run dev"
    volumes:
      - ./client/css:/trabacco-css:ro
      - /trabacco-css/node_modules
      - /trabacco-css/out
    ports:
      - 8082:8082

volumes:
  trabacco-data:
  # Volume for storing compiled sources, to speed up restarts
  trabacco-server-target:
  # Volume for storing maven dependencies, to speed up restarts
  trabacco-server-m2:
