version: "3.9"

services:
  spring-dev-server:
    image: openjdk:16-jdk-slim
    working_dir: /snustrack-server
    command: /snustrack-server/mvnw spring-boot:run
    volumes:
      - ./server:/snustrack-server
      - snustrack-data:/snustrack-server/data
      - snustrack-server-target:/snustrack-server/target
      - snustrack-server-m2:/root/.m2
    ports:
      - 8080:8080

  chart-dev-server:
    image: node:current-alpine3.13
    working_dir: /snustrack-chart
    command: /bin/sh -c "npm ci && npm run dev"
    volumes:
      - ./client/chart-generator:/snustrack-chart
      - /snustrack-chart/node_modules
      - /snustrack-chart/out
    ports:
      - 8081:8081

  css-dev-server:
    image: node:current-alpine3.13
    working_dir: /snustrack-css
    command: /bin/sh -c "npm ci && npm run dev"
    volumes:
      - ./client/css:/snustrack-css
      - /snustrack-css/node_modules
      - /snustrack-css/out
    ports:
      - 8082:8082

volumes:
  snustrack-data:
  # Volume for storing compiled sources, to speed up restarts
  snustrack-server-target:
  # Volume for storing maven dependencies, to speed up restarts
  snustrack-server-m2:
