version: "3.9"

services:
  server:
    build: .
    image: almgru/prilla:"$DOCKER_TAG"
    container_name: prilla
    volumes:
      - data:/app/data
      - ./config/application.properties:/app/application.properties
    networks:
    - reverse-proxy-net
    restart: unless-stopped

volumes:
  data:

networks:
  reverse-proxy-net:
    external: true
