version: "3.9"

services:
  server:
    build: .
    image: server:latest
    volumes:
      - data:/app/data
      - ./config/application.properties:/app/application.properties
    ports:
      - 8080:8080

volumes:
  data:
