version: "3.9"

services:
  spring-dev-server:
    image: openjdk:16-jdk-slim
    working_dir: /prilla-server
    command: /prilla-server/mvnw spring-boot:run
    volumes:
      - ./server:/prilla-server
      - ./config/dev-application.properties:/prilla-server/application.properties
      - server-target:/prilla-server/target
      - server-m2:/root/.m2
      - /prilla-server/data
    ports:
      - 8080:8080

  chart-dev-server:
    image: node:current-alpine3.13
    working_dir: /prilla-chart
    command: /bin/sh -c "npm ci && npm run dev"
    volumes:
      - ./client/chart-generator:/prilla-chart
      - /prilla-chart/node_modules
      - /prilla-chart/out
    ports:
      - 8081:8081

  css-dev-server:
    image: node:current-alpine3.13
    working_dir: /prilla-css
    command: /bin/sh -c "npm ci && npm run dev"
    volumes:
      - ./client/css:/prilla-css
      - /prilla-css/node_modules
      - /prilla-css/out
    ports:
      - 8082:8082

volumes:
  # Volume for storing compiled sources, to speed up restarts
  server-target:
  # Volume for storing maven dependencies, to speed up restarts
  server-m2:
