version: "3.9"

services:
  server:
    build: .
    image: almgru/prilla:$DOCKER_TAG
    container_name: prilla-${PRILLA_ENV}
    volumes:
      - data:/app/data
      - ./config/application-${PRILLA_ENV}.properties:/app/application.properties
    networks:
    - reverse-proxy-net
    restart: unless-stopped

volumes:
  data:

networks:
  reverse-proxy-net:
    external: true
