name: 'Build and deploy'
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  changes:
    name: 'Determine jobs to run'
    runs-on: 'ubuntu-latest'
    outputs:
      server: ${{ steps.changes.outputs.server }}
      android: ${{ steps.changes.outputs.android }}
    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'dorny/paths-filter@v2'
      id: changes
      with:
        token: ${{ secrets.PATH_PATHS_FILTER_READ_REPO_PULL_REQUESTS }}
        filters: |
          server:
            - 'server/**/*'
            - 'client/web/**/*'
          android:
            - 'client/android/**/*'

  build:
    name: 'Build and publish'
    runs-on: 'ubuntu-latest'
    needs: 'changes'
    if: ${{ needs.changes.outputs.server == 'true' }}
    outputs:
      docker_tag: ${{ steps.build_and_publish.outputs.docker_tag }}
    steps:
    - uses: 'actions/checkout@v3'

    - uses: './.github/actions/build-and-publish-docker-image'
      name: 'Build and publish docker image'
      id: build_and_publish
      with:
        docker_repository: '${{ secrets.DOCKER_HUB_USERNAME }}/prilla'
        registry_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        registry_token: ${{ secrets.DOCKER_HUB_TOKEN }}
        platforms: 'linux/amd64,linux/arm64'


  deploy:
    name: 'Deploy to runner'
    runs-on: 'self-hosted'
    needs: 'build'
    steps:
    - uses: 'actions/checkout@v3'

    - uses: './.github/actions/deploy-server-docker-image-to-runner'
      with:
        docker_tag: ${{ needs.build.outputs.docker_tag }}
        db_username: ${{ secrets.DB_USERNAME }}
        db_password: ${{ secrets.DB_PASSWORD }}
        web_username: ${{ secrets.WEB_USERNAME }}
        web_password: ${{ secrets.WEB_PASSWORD }}
